module.exports = [
  {
    id: 'contentId_1',
    actionId: 'action_3732987',
    contentTypeId: 'contentTypeId_1',
    occuranceTypeId: 'occuranceType1',
    name: 'Exodus 23:12',
    description: 'Read and reflect on this passage',
    body: 'Six days do your work, but on the seventh day do not work, so that your ox and your donkey may rest, and so that the slave born in your household and the foreigner living among you may be refreshed.',
    html: '',
    link: '',
  },
  {
    id: 'contentId_2',
    actionId: 'action_3732987',
    contentTypeId: 'contentTypeId_1',
    occuranceTypeId: 'occuranceType4',
    occuranceData: 2,
    name: 'Psalms 23:12',
    description: 'Read and reflect on this passage',
    body: 'Psalms llasd pasdpjfn adoan a ofnao af ao afnowef nwow lnnwonw l fwo',
    html: '',
    link: '',
  },
  {
    id: 'contentId_3',
    actionId: 'action_3732987',
    contentTypeId: 'contentTypeId_1',
    occuranceTypeId: 'occuranceType4',
    occuranceData: 2,
    name: 'Psalms 23:12',
    description: 'Read and reflect on this passage',
    body: 'Psalms llasd pasdpjfn adoan a ofnao af ao afnowef nwow lnnwonw l fwo',
    html: '',
    link: '',
  },
];
