module.exports = [
  {
    id: 'price_1IASfdD6Z8po8CMTYYRU5aTC',
    object: 'price',
    active: true,
    billing_scheme: 'per_unit',
    created: 1610856921,
    currency: 'usd',
    livemode: false,
    lookup_key: null,
    metadata: {},
    nickname: null,
    product: 'prod_ImLiyZDEY9QBl4',
    recurring: {
      aggregate_usage: null,
      interval: 'month',
      interval_count: 1,
      usage_type: 'licensed',
    },
    tiers_mode: null,
    transform_quantity: null,
    type: 'recurring',
    unit_amount: 5000,
    unit_amount_decimal: '5000',
  },
  {
    id: 'price_1IASfdD6Z8po8CMhfj8uybhg',
    object: 'price',
    active: true,
    billing_scheme: 'per_unit',
    created: 1610856921,
    currency: 'usd',
    livemode: false,
    lookup_key: null,
    metadata: {},
    nickname: null,
    product: 'prod_ImLiyZDEY9QBl4',
    recurring: {
      aggregate_usage: null,
      interval: 'month',
      interval_count: 1,
      usage_type: 'licensed',
    },
    tiers_mode: null,
    transform_quantity: null,
    type: 'recurring',
    unit_amount: 3000,
    unit_amount_decimal: '3000',
  },
  {
    id: 'price_1IASfdD6Z8po8CMhfj8uybhg',
    object: 'price',
    active: true,
    billing_scheme: 'per_unit',
    created: 1610856921,
    currency: 'usd',
    livemode: false,
    lookup_key: null,
    metadata: {},
    nickname: null,
    product: 'prod_ImLiyZDEY912313',
    recurring: {
      aggregate_usage: null,
      interval: 'month',
      interval_count: 1,
      usage_type: 'licensed',
    },
    tiers_mode: null,
    transform_quantity: null,
    type: 'recurring',
    unit_amount: 3000,
    unit_amount_decimal: '3000',
  },
];
