module.exports = [
  {
    id: 'cus_InD6MODH9LBA75',
    object: 'customer',
    address: null,
    balance: 0,
    created: 1611245739,
    currency: 'usd',
    default_source: null,
    delinquent: false,
    description: null,
    discount: null,
    email: null,
    invoice_prefix: '750B3E0',
    invoice_settings: {
      custom_fields: null,
      default_payment_method: null,
      footer: null,
    },
    livemode: false,
    metadata: {},
    name: null,
    next_invoice_sequence: 1,
    phone: null,
    preferred_locales: [],
    shipping: null,
    tax_exempt: 'none',
  },
];
